### ISSUE TITLE
你好作者，请问你遇见过这个问题吗

### ISSUE THREAD

**Issue by Winwina8** [alwaysfoggy/RPA#1]
Traceback (most recent call last):
  File "attack.py", line 487, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/RPA/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "attack.py", line 441, in main
    w, feature = sess.run([weights_tensor, opt_operations[0]],
UnboundLocalError: local variable 'weights_tensor' referenced before assignment

**Comment by bobere** [comment]
你好，你解决了吗，我也遇到了这个问题
